### ISSUE TITLE
Plugin service exit unexpectedly as SIP003 plugin

### ISSUE THREAD

**Issue by christaikobo** [zephyrchien/kaminari#6]
Server:
Debian 10 x64, shadowsocks-libev 3.3.5 with kaminaris linux gcc x64 0.5.6 as plugin, plugin_opts `ws;host=example.com;path=/ws` 

Client:
Openwrt 21.02.0 x64, shadowsocks-libev 3.3.5 with kaminaric linux musl x64 0.5.6 as plugin, plugin_opts `ws;host=example.com;path=/ws`

I noticed when the connection to server is unstable, kaminaric will sometimes cause shadowsocks instance to terminate, with log 
`daemon.err ss-redir[19787]: plugin service exit unexpectedly`

**Comment by zephyrchien** [comment]
Thank you for your detailed feedback! Kaminari does not write logs to a file, so it is hard to tell what's wrong with it. Please let me take a guess:

Could you find a `coredump` file left by Kaminari on your disk? If so, there might be a bug in the websocket library, though it has passed 50+ unit tests.

If not, it means Kaminari exited normally. (shadowsocks-libev always reports the same error when its subprocess exists.) It should be caused by an ACCEPT error, is there too many connections?

**Comment by christaikobo** [comment]
Where is the `coredump` file expected? I have checked the directory where kamianric resides, it does not seem to be there.  Unfortunately I reset my server for unrelated reasons, so can't check the server side. 

Just to add more information, I only noticed it because the connection to my server has been extremely unstable the past week. I don't think it is related to censorship, because a) it only happened during night time when traffic is high b) other people have been reporting similar connection issues c) it has recovered now. So background: network connection unstable. 

So the `daemon.err ss-redir[19787]: plugin service exit unexpectedly` happened at least 2 separate times during different nights, when I was watch streaming service with my PC browser. I have also got a bunch of services running in the background like a DNS service that goes through shadowsocks which also serves for some of my family members in different locations. Should be quite some connections. I started to notice stutters during the stream, so I went to the openwrt log, and got the `daemon.err ss-redir[19787]: plugin service exit unexpectedly` error. I have got a x64 openwrt router with 4 threads, so I setup 4 shadowsocks instances. Some of them exited, and before long all 4 exited. I restarted shadowsocks, but the connection is still terrible. After that some (but not all) of the 4 shadowoscks instances exited. I gave up and went to bed. And it happened at least 2 times. 

I wish I can provide more information, instead of just telling a story like this:(

**Comment by zephyrchien** [comment]
It seems OpenWrt does not enable coredump by default, see:

```bash
ulimit -c
```
The result is 0.

And if coredump is allowed(`ulimit -c != 0`), you can check its location with:

```bash
sysctl kernel.core_pattern
```
See if there is something like `core.kaminaric`.

---

The error was reported by `ss-redir`, so I think it was a client-side problem, right? As a proxy program, the most frequently occurred problem is that **the number of open files exceeds the limit**. Because processing one connection requires 2 FD, while on linux the default FD limit is 1024, or even smaller on a few distributions. By default, only 512 connections can be processed concurrently. When there are "too many" connections, an ACCEPT error will be raised, Kaminari is designed to exit directly in this case.

Typically shadowsocks and its plugin will have the same number of connections, was shadowsocks started with a higher fd limit? E.g: use systemd with a higher `DefaultLimitNOFILESoft`; use shadowsocks-libv's builtin `-n` option.

**Comment by christaikobo** [comment]
Thanks for the response!

1. Indeed the openwrt kernel disabled core dump. There does not seem to be a simple way to enable it. 
2. Shadowsocks-libev was not started with -n option.
3. I think when connectivity is intermittent, the DoH request could quickly pile up, causing connection number to rise. Is it possible not to exit? I will switch back to v2ray-plugin and see if it behaves the same.

**Comment by christaikobo** [comment]
Couple of updates:

1. v2ray-plugin does not seem to exit under the same situation. 
2. Using v2ray-plugin on the client side with kaminaris on the server (as SIP003 plugin) seems to be causing some kind of connection problem with google drive api. All my backup to google drive failed during this. Once I switched back to kaminaric + kaminaris, it works just fine. (I did add `mux=0`)

**Comment by christaikobo** [comment]
Last update:

I have been using kaminari for over 2 months now, it's working great. 
I think you are right that too many connections caused the exit. But under normal condition, there won't be so many connections.
